### ISSUE TITLE
Updating PIR for 2.17 error

### ISSUE THREAD

**Issue by lowanger** [paviro/MMM-PIR-Sensor#124]
Hello everyone,

i am at a wits end as to update the PIR sensor module - can anyone help me with it?

---

pi@magicmirrorpi:~/MagicMirror/modules/MMM-PIR-Sensor $ npm install

> Magic-Mirror-Module-PIR-Sensor@1.1.0 postinstall /home/pi/MagicMirror/modules/MMM-PIR-Sensor
> electron-rebuild -e ../../node_modules/electron

✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
make: Verzeichnis „/home/pi/MagicMirror/modules/MMM-PIR-Sensor/node_modules/epoll/build“ wird betreten
  CXX(target) Release/obj.target/epoll/src/epoll.o
In file included from ../../nan/nan.h:2884:0,
                 from ../src/epoll.cc:15:
../../nan/nan_typedarray_contents.h: In constructor ‘Nan::TypedArrayContents<T>::TypedArrayContents(v8::Local<v8::Value>)’:
../../nan/nan_typedarray_contents.h:34:43: error: ‘class v8::ArrayBuffer’ has no member named ‘GetContents’; did you mean ‘IsContext’?
       data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
                                           ^~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
epoll.target.mk:117: die Regel für Ziel „Release/obj.target/epoll/src/epoll.o“ scheiterte
make: Verzeichnis „/home/pi/MagicMirror/modules/MMM-PIR-Sensor/node_modules/epoll/build“ wird verlassen
make: *** [Release/obj.target/epoll/src/epoll.o] Fehler 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/MagicMirror/modules/MMM-PIR-Sensor/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.14.27-v7+
gyp ERR! command "/usr/bin/node" "/home/pi/MagicMirror/modules/MMM-PIR-Sensor/node_modules/.bin/node-gyp" "rebuild" "--target=13.5.1" "--arch=arm" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-PIR-Sensor/node_modules/epoll
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1

Error: make: Verzeichnis „/home/pi/MagicMirror/modules/MMM-PIR-Sensor/node_modules/epoll/build“ wird betreten
  CXX(target) Release/obj.target/epoll/src/epoll.o
In file included from ../../nan/nan.h:2884:0,
                 from ../src/epoll.cc:15:
../../nan/nan_typedarray_contents.h: In constructor ‘Nan::TypedArrayContents<T>::TypedArrayContents(v8::Local<v8::Value>)’:
../../nan/nan_typedarray_contents.h:34:43: error: ‘class v8::ArrayBuffer’ has no member named ‘GetContents’; did you mean ‘IsContext’?
       data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
                                           ^~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
epoll.target.mk:117: die Regel für Ziel „Release/obj.target/epoll/src/epoll.o“ scheiterte
make: Verzeichnis „/home/pi/MagicMirror/modules/MMM-PIR-Sensor/node_modules/epoll/build“ wird verlassen
make: *** [Release/obj.target/epoll/src/epoll.o] Fehler 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/MagicMirror/modules/MMM-PIR-Sensor/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.14.27-v7+
gyp ERR! command "/usr/bin/node" "/home/pi/MagicMirror/modules/MMM-PIR-Sensor/node_modules/.bin/node-gyp" "rebuild" "--target=13.5.1" "--arch=arm" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-PIR-Sensor/node_modules/epoll
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/home/pi/MagicMirror/modules/MMM-PIR-Sensor/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/home/pi/MagicMirror/modules/MMM-PIR-Sensor/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/home/pi/MagicMirror/modules/MMM-PIR-Sensor/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/home/pi/MagicMirror/modules/MMM-PIR-Sensor/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/home/pi/MagicMirror/modules/MMM-PIR-Sensor/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/home/pi/MagicMirror/modules/MMM-PIR-Sensor/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/home/pi/MagicMirror/modules/MMM-PIR-Sensor/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/home/pi/MagicMirror/modules/MMM-PIR-Sensor/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/home/pi/MagicMirror/modules/MMM-PIR-Sensor/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/home/pi/MagicMirror/modules/MMM-PIR-Sensor/node_modules/rxjs/internal/Subscriber.js:143:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! Magic-Mirror-Module-PIR-Sensor@1.1.0 postinstall: `electron-rebuild -e ../../node_modules/electron`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the Magic-Mirror-Module-PIR-Sensor@1.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-11-20T16_05_03_086Z-debug.log

**Comment by lowanger** [comment]
Deleted folder -> git pull -> isntalled -> kinda works now. 

First motion gets detected, second not -> mirror stays dark. Different issue
