### ISSUE TITLE
EACCES /sys/class/gpio/export

### ISSUE THREAD

**Issue by Patrick-Remy** [paviro/MMM-PIR-Sensor#19]
After installing this module and following the README I got this error message:
```
0|mm       | { Error: EACCES: permission denied, open '/sys/class/gpio/export'
0|mm       |     at Error (native)
0|mm       |     at Object.fs.openSync (fs.js:640:18)
0|mm       |     at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
0|mm       |     at Object.fs.writeFileSync (fs.js:1343:33)
0|mm       |     at new Gpio (/home/patrick/MagicMirror/modules/MMM-PIR-Sensor/node_modules/onoff/onoff.js:88:8)
0|mm       |     at Class.socketNotificationReceived (/home/patrick/MagicMirror/modules/MMM-PIR-Sensor/node_helper.js:44:18)
0|mm       |     at Socket.<anonymous> (/home/patrick/MagicMirror/modules/node_modules/node_helper/index.js:98:10)
0|mm       |     at emitTwo (events.js:106:13)
0|mm       |     at Socket.emit (events.js:191:7)
0|mm       |     at /home/patrick/MagicMirror/node_modules/socket.io/lib/socket.js:503:12
0|mm       |   errno: -13,
0|mm       |   code: 'EACCES',
0|mm       |   syscall: 'open',
0|mm       |   path: '/sys/class/gpio/export' }

```

For me, it seems that the README is wrong, because the given command creates a new user gpio with primary group pi. Instead of adding the pi user to gpio group.
`Add your user (pi?) to the gpio group by executing sudo useradd -g pi gpio.`

After realizing, I also added my user to the gpio group by executing `sudo usermod -a -G gpio pi` and it worked. Deleting the previously created user `gpio` (via `sudo userdel -r gpio`) prompts no error message.

**Comment by Patrick-Remy** [comment]
I missed another issue. When launching manually, after the PIR-Sensor detects a motion, the output promts: `[sudo] password for pi:`. And the HDMI output is turning off/on/off/on/off/on...
